# Generated by Django 5.0.4 on 2024-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
